// Copyright 2026 Jeff Lafitte
// SPDX-License-Identifier: AGPL-3.0-or-later

#include <agnes/internal_/elements_are_assignable.h>

#include <tuple>

static_assert(   agnes::internal_::elements_are_assignable_v<      std::tuple<      int& >  , std::tuple<      int  >>);
static_assert(   agnes::internal_::elements_are_assignable_v<      std::tuple<      int& >  , std::tuple<      int& >>);
static_assert(   agnes::internal_::elements_are_assignable_v<      std::tuple<      int& >  , std::tuple<      int&&>>);
static_assert(   agnes::internal_::elements_are_assignable_v<      std::tuple<      int& >  , std::tuple<const int  >>);
static_assert(   agnes::internal_::elements_are_assignable_v<      std::tuple<      int& >  , std::tuple<const int& >>);
static_assert(   agnes::internal_::elements_are_assignable_v<      std::tuple<      int& >  , std::tuple<const int&&>>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<      int&&>  , std::tuple<      int  >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<      int&&>  , std::tuple<      int& >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<      int&&>  , std::tuple<      int&&>>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<      int&&>  , std::tuple<const int  >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<      int&&>  , std::tuple<const int& >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<      int&&>  , std::tuple<const int&&>>);
static_assert(   agnes::internal_::elements_are_assignable_v<const std::tuple<      int& >  , std::tuple<      int  >>);
static_assert(   agnes::internal_::elements_are_assignable_v<const std::tuple<      int& >  , std::tuple<      int& >>);
static_assert(   agnes::internal_::elements_are_assignable_v<const std::tuple<      int& >  , std::tuple<      int&&>>);
static_assert(   agnes::internal_::elements_are_assignable_v<const std::tuple<      int& >  , std::tuple<const int  >>);
static_assert(   agnes::internal_::elements_are_assignable_v<const std::tuple<      int& >  , std::tuple<const int& >>);
static_assert(   agnes::internal_::elements_are_assignable_v<const std::tuple<      int& >  , std::tuple<const int&&>>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<      int&&>  , std::tuple<      int  >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<      int&&>  , std::tuple<      int& >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<      int&&>  , std::tuple<      int&&>>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<      int&&>  , std::tuple<const int  >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<      int&&>  , std::tuple<const int& >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<      int&&>  , std::tuple<const int&&>>);

static_assert(   agnes::internal_::elements_are_assignable_v<      std::tuple<      int& >& , std::tuple<      int  >>);
static_assert(   agnes::internal_::elements_are_assignable_v<      std::tuple<      int& >& , std::tuple<      int& >>);
static_assert(   agnes::internal_::elements_are_assignable_v<      std::tuple<      int& >& , std::tuple<      int&&>>);
static_assert(   agnes::internal_::elements_are_assignable_v<      std::tuple<      int& >& , std::tuple<const int  >>);
static_assert(   agnes::internal_::elements_are_assignable_v<      std::tuple<      int& >& , std::tuple<const int& >>);
static_assert(   agnes::internal_::elements_are_assignable_v<      std::tuple<      int& >& , std::tuple<const int&&>>);
static_assert(   agnes::internal_::elements_are_assignable_v<      std::tuple<      int&&>& , std::tuple<      int  >>);
static_assert(   agnes::internal_::elements_are_assignable_v<      std::tuple<      int&&>& , std::tuple<      int& >>);
static_assert(   agnes::internal_::elements_are_assignable_v<      std::tuple<      int&&>& , std::tuple<      int&&>>);
static_assert(   agnes::internal_::elements_are_assignable_v<      std::tuple<      int&&>& , std::tuple<const int  >>);
static_assert(   agnes::internal_::elements_are_assignable_v<      std::tuple<      int&&>& , std::tuple<const int& >>);
static_assert(   agnes::internal_::elements_are_assignable_v<      std::tuple<      int&&>& , std::tuple<const int&&>>);
static_assert(   agnes::internal_::elements_are_assignable_v<const std::tuple<      int& >& , std::tuple<      int  >>);
static_assert(   agnes::internal_::elements_are_assignable_v<const std::tuple<      int& >& , std::tuple<      int& >>);
static_assert(   agnes::internal_::elements_are_assignable_v<const std::tuple<      int& >& , std::tuple<      int&&>>);
static_assert(   agnes::internal_::elements_are_assignable_v<const std::tuple<      int& >& , std::tuple<const int  >>);
static_assert(   agnes::internal_::elements_are_assignable_v<const std::tuple<      int& >& , std::tuple<const int& >>);
static_assert(   agnes::internal_::elements_are_assignable_v<const std::tuple<      int& >& , std::tuple<const int&&>>);
static_assert(   agnes::internal_::elements_are_assignable_v<const std::tuple<      int&&>& , std::tuple<      int  >>);
static_assert(   agnes::internal_::elements_are_assignable_v<const std::tuple<      int&&>& , std::tuple<      int& >>);
static_assert(   agnes::internal_::elements_are_assignable_v<const std::tuple<      int&&>& , std::tuple<      int&&>>);
static_assert(   agnes::internal_::elements_are_assignable_v<const std::tuple<      int&&>& , std::tuple<const int  >>);
static_assert(   agnes::internal_::elements_are_assignable_v<const std::tuple<      int&&>& , std::tuple<const int& >>);
static_assert(   agnes::internal_::elements_are_assignable_v<const std::tuple<      int&&>& , std::tuple<const int&&>>);

static_assert(   agnes::internal_::elements_are_assignable_v<      std::tuple<      int& >&&, std::tuple<      int  >>);
static_assert(   agnes::internal_::elements_are_assignable_v<      std::tuple<      int& >&&, std::tuple<      int& >>);
static_assert(   agnes::internal_::elements_are_assignable_v<      std::tuple<      int& >&&, std::tuple<      int&&>>);
static_assert(   agnes::internal_::elements_are_assignable_v<      std::tuple<      int& >&&, std::tuple<const int  >>);
static_assert(   agnes::internal_::elements_are_assignable_v<      std::tuple<      int& >&&, std::tuple<const int& >>);
static_assert(   agnes::internal_::elements_are_assignable_v<      std::tuple<      int& >&&, std::tuple<const int&&>>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<      int&&>&&, std::tuple<      int  >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<      int&&>&&, std::tuple<      int& >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<      int&&>&&, std::tuple<      int&&>>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<      int&&>&&, std::tuple<const int  >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<      int&&>&&, std::tuple<const int& >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<      int&&>&&, std::tuple<const int&&>>);
static_assert(   agnes::internal_::elements_are_assignable_v<const std::tuple<      int& >&&, std::tuple<      int  >>);
static_assert(   agnes::internal_::elements_are_assignable_v<const std::tuple<      int& >&&, std::tuple<      int& >>);
static_assert(   agnes::internal_::elements_are_assignable_v<const std::tuple<      int& >&&, std::tuple<      int&&>>);
static_assert(   agnes::internal_::elements_are_assignable_v<const std::tuple<      int& >&&, std::tuple<const int  >>);
static_assert(   agnes::internal_::elements_are_assignable_v<const std::tuple<      int& >&&, std::tuple<const int& >>);
static_assert(   agnes::internal_::elements_are_assignable_v<const std::tuple<      int& >&&, std::tuple<const int&&>>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<      int&&>&&, std::tuple<      int  >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<      int&&>&&, std::tuple<      int& >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<      int&&>&&, std::tuple<      int&&>>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<      int&&>&&, std::tuple<const int  >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<      int&&>&&, std::tuple<const int& >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<      int&&>&&, std::tuple<const int&&>>);

static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int& >  , std::tuple<      int  >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int& >  , std::tuple<      int& >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int& >  , std::tuple<      int&&>>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int& >  , std::tuple<const int  >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int& >  , std::tuple<const int& >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int& >  , std::tuple<const int&&>>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int&&>  , std::tuple<      int  >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int&&>  , std::tuple<      int& >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int&&>  , std::tuple<      int&&>>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int&&>  , std::tuple<const int  >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int&&>  , std::tuple<const int& >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int&&>  , std::tuple<const int&&>>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int& >  , std::tuple<      int  >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int& >  , std::tuple<      int& >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int& >  , std::tuple<      int&&>>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int& >  , std::tuple<const int  >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int& >  , std::tuple<const int& >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int& >  , std::tuple<const int&&>>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int&&>  , std::tuple<      int  >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int&&>  , std::tuple<      int& >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int&&>  , std::tuple<      int&&>>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int&&>  , std::tuple<const int  >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int&&>  , std::tuple<const int& >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int&&>  , std::tuple<const int&&>>);

static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int& >& , std::tuple<      int  >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int& >& , std::tuple<      int& >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int& >& , std::tuple<      int&&>>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int& >& , std::tuple<const int  >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int& >& , std::tuple<const int& >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int& >& , std::tuple<const int&&>>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int&&>& , std::tuple<      int  >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int&&>& , std::tuple<      int& >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int&&>& , std::tuple<      int&&>>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int&&>& , std::tuple<const int  >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int&&>& , std::tuple<const int& >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int&&>& , std::tuple<const int&&>>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int& >& , std::tuple<      int  >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int& >& , std::tuple<      int& >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int& >& , std::tuple<      int&&>>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int& >& , std::tuple<const int  >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int& >& , std::tuple<const int& >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int& >& , std::tuple<const int&&>>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int&&>& , std::tuple<      int  >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int&&>& , std::tuple<      int& >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int&&>& , std::tuple<      int&&>>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int&&>& , std::tuple<const int  >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int&&>& , std::tuple<const int& >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int&&>& , std::tuple<const int&&>>);

static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int& >&&, std::tuple<      int  >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int& >&&, std::tuple<      int& >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int& >&&, std::tuple<      int&&>>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int& >&&, std::tuple<const int  >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int& >&&, std::tuple<const int& >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int& >&&, std::tuple<const int&&>>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int&&>&&, std::tuple<      int  >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int&&>&&, std::tuple<      int& >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int&&>&&, std::tuple<      int&&>>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int&&>&&, std::tuple<const int  >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int&&>&&, std::tuple<const int& >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<      std::tuple<const int&&>&&, std::tuple<const int&&>>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int& >&&, std::tuple<      int  >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int& >&&, std::tuple<      int& >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int& >&&, std::tuple<      int&&>>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int& >&&, std::tuple<const int  >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int& >&&, std::tuple<const int& >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int& >&&, std::tuple<const int&&>>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int&&>&&, std::tuple<      int  >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int&&>&&, std::tuple<      int& >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int&&>&&, std::tuple<      int&&>>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int&&>&&, std::tuple<const int  >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int&&>&&, std::tuple<const int& >>);
static_assert( ! agnes::internal_::elements_are_assignable_v<const std::tuple<const int&&>&&, std::tuple<const int&&>>);
